version: '3'
services:

  geth_client:
    image: tournament/eth_go_client:latest
    restart: always
    networks:
      geth_back:
        aliases:
          - geth_client
    ports:
      - "30300:30303"
      - "30300:30303/udp"
    environment:
      - GETH_NODE_TYPE="MASTER"

  eth_net_front:
    image: tournament/eth_net_front:latest
    environment:
      - COMPOSE_EXPORT_PUTTY=$COMPOSE_EXPORT_VAR
    restart: always
    networks:
      geth_back:
        aliases:
          - eth_net_front
    ports:
      - "3010:3010"

  apollo_booster:
    image: tournament/apollo_booster:latest
    restart: always
    networks:
      geth_back:
        aliases:
          - apollo_booster
    ports:
      - "8080:8080"

networks:
  geth_back:
